In [ ]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# The LabelEncoder encodes a sequence of bases as a sequence of integers.
#Create an instance of LabelEncoder()
integer_encoder = LabelEncoder()  # Height = ["short", "medium", "tall"] ----> Height = [1, 0, 2]

# The OneHotEncoder converts an array of integers to a sparse matrix where 
# each row corresponds to one possible value of each feature.
#Create an instance of One-hot-encoder
one_hot_encoder = OneHotEncoder(categories=[list(range(4))]) #'auto'  Gender = [Male, Female] -----> Gender = [[0 , 1], 
 #                                                                                                             [1 , 0]]

In [ ]:
sequence =list("AATGTC")  #['A', 'A', 'T', 'G', 'T', 'C']
integer_encoded = integer_encoder.fit_transform(sequence)
print(integer_encoded)
print(type(integer_encoded))

[0 0 3 2 3 1]
<class 'numpy.ndarray'>


In [ ]:
integer_encoded = integer_encoded.reshape(-1, 1)
print("Vetical_integer_encoded = \n", integer_encoded)

Vetical_integer_encoded = 
 [[0]
 [0]
 [3]
 [2]
 [3]
 [1]]


In [ ]:
one_hot_encoded = one_hot_encoder.fit_transform(integer_encoded)
print(one_hot_encoded)
print(type(one_hot_encoded))

  (0, 0)	1.0
  (1, 0)	1.0
  (2, 3)	1.0
  (3, 2)	1.0
  (4, 3)	1.0
  (5, 1)	1.0
<class 'scipy.sparse.csr.csr_matrix'>


In [ ]:
input_features = one_hot_encoded.toarray()
print('One hot encoding of Sequence:\n', input_features ,'\n')
print(type(input_features))

One hot encoding of Sequence:
 [[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]] 

<class 'numpy.ndarray'>
